[[servers]]
	[servers.eu]
		ip = '127.0.0.1'
		port = 7331
		name = 'EU'
		max_players = 20
		tps = 20
#	[servers.us]
#    	ip = '127.0.0.2'
#    	port = 7331
#    	name = 'US'
#    	max_players = 40
#    	tps = 20