[[texture]]
name = "Ground"
file = "Ground.vif"
    	
[[font]]
name = "Monogram"
file = "Monogram.vff"
		
[[shader]]
name = "SpriteShader"
file = "Sprite.glsl"

[[shader]]
name = "MeshShader"
file = "Mesh.glsl"

[[shader]]
name = "ColorShader"
file = "Color.glsl"
    
[[sound]]
name = "Fireplace"
file = "Fireplace.vsf"