assets_root = 'Assets'
assets_textures = 'Textures'
assets_fonts = 'Fonts'
assets_sounds = 'Sounds'
assets_shaders = 'Shaders'
fullscreen = false
client_width = 1280
client_height = 720
player_name = 'VoOoLoX'